//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teacherscompanion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public Classes()
        {
            this.Students = new HashSet<Students>();
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Students> Students { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
