//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teacherscompanion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Id { get; set; }
        public int StudentsRFid { get; set; }
        public int SessionsId { get; set; }
    
        public virtual Students Student { get; set; }
        public virtual Sessions Session { get; set; }
    }
}
