//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teacherscompanion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public Sessions()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ClassesId { get; set; }
    
        public virtual Classes Class { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
    }
}
